repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=5000"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint --fail-under=8 robodroid/ --output-format=colorized
        language: system
        always_run: true
        pass_filenames: false
        types: [python]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --disallow-untyped-calls --disallow-untyped-defs --disallow-incomplete-defs --ignore-missing-imports .
        language: system
        always_run: true
        pass_filenames: false
        types: [python]
