id: Workflow ID

init:
  install:
    - Path to the .apk to install
  clear:
    - Package to clean with "pm clear <package-name>"

behaviors:
  - id: ID of the step in this workflow
    name: ID of the script in the RoboDroid library to execute (.e.g. k9-mail-account-setup)
    type: Type of the step (e.g. 'frida-behavior', 'adb')
    inputs:
      - id: input ID
        value: value for this input (use 'robodroid.outputs.<step_id>.<step_output>' to use the outputs of previous steps)

    outputs:
      - id: output ID
        value: value for this output
