id: Config ID
host: localhost
port: 5037
type: Device type (redroid, avd, waydroid, real-device)
device_name: Device name (e.g. 'robodroid-test')

init:
  packages:
    - Path to the .apk to install

workflow:
  - id: TOCHANGE ID of the script in the RoboDroid library to execute (.e.g. gmail-account-setup)
    name: TODO
    type: TODO
    inputs:
      - id: input ID
        value: value for this input

    outputs:
      - id: output ID
        value: value for this output
