id: Config ID
host: localhost
port: 5037
type: Device type (redroid, avd, waydroid, real-device)
device-name: Device name (e.g. 'robodroid-test')

init:
  packages:
    - Path to the .apk to install

behaviors:
  - id: ID of the script in the RoboDroid library to execute (.e.g. gmail-account-setup)
    inputs:
      - id: input ID
        value: value for this input
